services:
  app:
    build:
      context: . # Build context is the project root
      dockerfile: Dockerfile
    container_name: language_exercise_app
    ports:
      - "${APP_PORT:-8501}:8501" # Expose Streamlit port, default 8501
      - "5678:5678" # Expose debug port
    volumes:
      # Mount the source code for development (optional, remove for production)
      # Allows code changes without rebuilding image
      - ./language_agent:/app/language_agent
      - ./data:/data
    restart: unless-stopped
    env_file:
      - .env
    # Environment variables needed by the app
    environment:
      OPENAI_API_KEY:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_REGION:
      S3_BUCKET_NAME:
      DEBUG: True
    # watchfiles + code is mounted via volume - makes sure that code changes automatically restart the streamlit server
    entrypoint: ["watchfiles", "streamlit run /app/language_agent/frontend/app.py --server.port=8501 --server.address=0.0.0.0", "/app/language_agent"]
    # entrypoint: ["streamlit", "run", "/app/language_agent/frontend/app.py", "--server.port=8501", "--server.address=0.0.0.0"]

