version: '3.8'

services:
  api:
    build:
      context: ./backend-flask
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend-flask/words.db:/app/words.db
    environment:
      - FLASK_ENV=development
    networks:
      - lang-portal-network

  frontend:
    build:
      context: ./frontend-react
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - API_URL=http://localhost:8000
    depends_on:
      - api
    networks:
      - lang-portal-network

networks:
  lang-portal-network:
    driver: bridge