services:
  ai-agents:
    build: .
    environment:
      PYTHONUNBUFFERED: 1
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    entrypoint: ["sleep", "infinity"]
    volumes:
      - ./app:/app
    ports:
      - "5678:5678"  # Expose debugpy port
