services:
  ai-agents:
    build: .
    environment:
      PYTHONUNBUFFERED: 1
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    entrypoint: ["watchfiles", "sleep infinity", "/app"]
    volumes:
      - ./app:/app
