services:
  tgi-server:
    image: ghcr.io/huggingface/text-generation-inference:2.4.0-intel-cpu
    container_name: tgi-server
    ports:
      - ${LLM_ENDPOINT_PORT:-8008}:80
    volumes:
      - "${DATA_PATH:-./data}:/data"
    shm_size: 1g
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      HF_TOKEN: ${HF_TOKEN}
      host_ip: ${host_ip}
      LLM_ENDPOINT_PORT: ${LLM_ENDPOINT_PORT}
      MAX_INPUT_TOKENS: ${MAX_INPUT_TOKENS:-2048}
      MAX_TOTAL_TOKENS: ${MAX_TOTAL_TOKENS:-4096}
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://${host_ip}:${LLM_ENDPOINT_PORT}/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 100
    command: --model-id ${LLM_MODEL_ID} --cuda-graphs 0
  speecht5-service:
    image: ${REGISTRY:-opea}/speecht5:${TAG:-latest}
    container_name: speecht5-service
    ports:
      - ${SPEECHT5_PORT:-7055}:7055
    ipc: host
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7055/health"]
      interval: 10s
      timeout: 6s
      retries: 18
  tts-speecht5:
    image: ${REGISTRY:-opea}/tts:${TAG:-latest}
    container_name: tts-speecht5-service
    ports:
      - ${TTS_PORT:-9088}:9088
    ipc: host
    environment:
      TTS_ENDPOINT: ${TTS_ENDPOINT}
      TTS_COMPONENT_NAME: ${TTS_COMPONENT_NAME:-OPEA_SPEECHT5_TTS}
    depends_on:
      speecht5-service:
        condition: service_healthy
  llm-tts:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: llm-tts
    depends_on:
      - tgi-server
      - speecht5-service
      - tts-speecht5
    ports:
      - "3008:8888"
    environment:
      - no_proxy=${no_proxy}
      - https_proxy=${https_proxy}
      - http_proxy=${http_proxy}
      - MEGA_SERVICE_HOST_IP=${MEGA_SERVICE_HOST_IP}
      - LLM_SERVER_HOST_IP=${LLM_SERVER_HOST_IP:-tgi-server}
      - LLM_SERVER_PORT=${LLM_SERVER_PORT:-80}
      - LLM_MODEL_ID=${LLM_MODEL_ID}
      - SPEECHT5_SERVER_HOST_IP=${SPEECHT5_SERVER_HOST_IP:-speecht5-service}
      - SPEECHT5_SERVER_PORT=${SPEECHT5_SERVER_PORT:-7055}
      - TTS_SPEECHT5_SERVER_HOST_IP=${TTS_SPEECHT5_SERVER_HOST_IP:-tts-speecht5-service}
      - TTS_SPEECHT5_SERVER_PORT=${TTS_SPEECHT5_SERVER_PORT:-9088}
    ipc: host
    restart: always


networks:
  default:
    driver: bridge